### ISSUE TITLE
Fails to Receive

### ISSUE THREAD

**Issue by CircusDad** [hectorchu/gonano#2]
Windows 10 and Linux.
I used the program to successfully create an account in Windows 10 and then I sent it a small amount via https://nano-faucet.org/
I could not get transaction to be received using the wallet.  I assumed it might be another Windows 10 issue so I built the program in ubuntu, created another wallet and tried again.

`./main add -w0
Enter password:
Added account nano_1tjj6r5f5azmjjduwh7hrxsqcq19moox1939dhczbh58h4fejpasat8qx6ab`

the command 
`./main receive -w0` 
did not work (still shows as pending in https://nanocrawler.cc/explorer/ )

the command  
`./main receive -a nano_1tjj6r5f5azmjjduwh7hrxsqcq19moox1939dhczbh58h4fejpasat8qx6ab`
also did not work.

**Comment by hectorchu** [comment]
Was there an error message?

**Comment by CircusDad** [comment]
```
./main list -w0
nano_1tjj6r5f5azmjjduwh7hrxsqcq19moox1939dhczbh58h4fejpasat8qx6ab
```

**Comment by hectorchu** [comment]
My Nano Ninja basically has a problem today. It never had a problem before when I was developing this library. I think the best thing to do is to wait for the guy to restart his service. I will see if it is working tomorrow.

**Comment by hectorchu** [comment]
I just checked and My Nano Ninja is working again. So you should be able to receive the pending amount.

**Comment by CircusDad** [comment]
Thank you.  That did work now.  Reach out if you ever need a feature tested.  I don't actually have a specific use for gonano quite yet but I am learning Go and thought I would do a little testing.  Thank you again.

**Comment by hectorchu** [comment]
You're welcome and no worries about not needing gonano for the time being. I'm building a graphical version of gonano that can be used as an everyday wallet, so maybe keep an eye out for that when it becomes ready.
