### ISSUE TITLE
Used your plugin for Woocommerce (Gonano payment gateway), having serious issues

### ISSUE THREAD

**Issue by metroidst** [hectorchu/gonano#8]
Used your Gonano plugin for WooCommerce, having big issues. One client send a transaction to the intermediate wallet address which didn't send it to the recepient wallet address (nano_3ajaewy49s1wz8jjbygbzf9wcoa8bskcc3b7b6xz68odt3qia6mu7cytfbkp):

https://nanocrawler.cc/explorer/block/D21448519EC189AA7F32E5FE31F17FAEDD621365498A04A3DA831BE844CA9004

https://nanocrawler.cc/explorer/account/nano_1gpshygkby1a4cw4q981m6z7cj84hqy6enj6akcn8d6cf86mtu5kmaw4xxj5/history

What are we doing now?

**Comment by hectorchu** [comment]
Refunded.

The fault is with the NANO network which is still degraded from the spam attack. It'll be like that until v22 fixes everything.
